# Generated by Django 4.2.1 on 2023-05-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Homepage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("job_title", models.CharField(max_length=100)),
                ("punchline", models.TextField(max_length=100)),
                ("profile_pic", models.ImageField(upload_to="images/")),
                ("about_me", models.TextField()),
                ("linkedin", models.URLField()),
                ("github", models.URLField()),
                ("email", models.EmailField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("logo", models.ImageField(upload_to="images/skill_logos/")),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=100)),
                ("job_title", models.CharField(max_length=100)),
                ("logo", models.ImageField(upload_to="images/company_logos/")),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("company_description", models.TextField()),
                ("experience_description", models.TextField()),
                ("skills", models.ManyToManyField(to="home.skill")),
            ],
        ),
    ]
