# Generated by Django 4.2.1 on 2023-05-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_homepage_experiences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="punchline",
            field=models.TextField(max_length=255),
        ),
    ]
