# Generated by Django 4.2.1 on 2023-05-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_homepage_punchline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name_plural": "Home page"},
        ),
        migrations.RemoveField(
            model_name="skill",
            name="description",
        ),
    ]
