# Generated by Django 4.2.1 on 2023-05-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_skill_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="present",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
