# Generated by Django 4.2.1 on 2023-05-08 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_responsibility_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="experience",
            old_name="description",
            new_name="experience_description",
        ),
    ]
