# Generated by Django 4.2.1 on 2023-05-08 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_experience_experience_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="responsibility",
            name="Experience",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.experience",
            ),
        ),
    ]
