# Generated by Django 4.2.1 on 2023-05-08 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_responsibility_experience"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="responsibility",
            options={"verbose_name_plural": "Responsibilities"},
        ),
        migrations.AlterField(
            model_name="responsibility",
            name="Experience",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.experience"
            ),
        ),
    ]
