# Generated by Django 4.2.1 on 2023-07-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_alter_responsibility_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="cv",
            field=models.URLField(null=True),
        ),
    ]
