# Generated by Django 4.2.1 on 2023-07-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_homepage_cv"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="contact_desc",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="cv",
            field=models.URLField(),
        ),
    ]
