# Generated by Django 4.2.1 on 2023-07-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_homepage_contact_desc_alter_homepage_cv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="contact_desc",
            field=models.TextField(max_length=400, null=True),
        ),
    ]
